### ISSUE TITLE
Flatpak on Ubuntu not working

### ISSUE THREAD

**Issue by JeckPeppinger** [jmlich/geotagging#49]
I tried a while to get geotagging to run on ubunutu24.04, but no chance.
Does not start via flatpak...

This status is unchanged for many month, i tried before with ubuntu 23.10.
Still this problem persists.

Is this project terminated?
How to get it to run on Ubuntu 24.04?

**Comment by jmlich** [comment]
I have rebuilt flatpak packages 2 months ago due to incompatibility in platform.

It works for me on Fedora 40. The issue tracker doesn't contain any other issue about flatpak nor ubuntu issues so I wasn't aware that anything is broken.

Can you provides some logs e.g. to run it from terminal `flatpak run com.github.jmlich.geotagging` ?

My use case for this application is once per year when I am preparing navigation competition. It contains all the features I need so I am not making new one. Unfortunately flatpak/linux/windows pipelines are changing more often. Feel free to debug issue and send pull request.

**Comment by JeckPeppinger** [comment]
Oh thanks, for the fast response, i tried via command line `flatpak run com.github.jmlich.geotagging $@` and the program came up.
It did not start via the .desktop file which was installed by the install procedure. I tried to change the exec part in the .desktop file, but whatever tried did not work.

So i made a simple bash script with the above flatpak command and linked it into /usr/local/bin in the $PATH, now the .desktop file works well too.

Thanks, all fine, and thanks for the great tool!
